name:                pipes-graphics
version:             0.1.0.0
github:              "fabricatedmath/pipes-graphics"
license:             BSD3
author:              "Charles Durham"
maintainer:          "fabricatedmath@gmail.com"
copyright:           "2018 Charles Durham"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/fabricatedmath/pipes-graphics#readme>

dependencies:
- base >= 4.7 && < 5
- pipes
- pipes-safe
- ffmpeg-light
- repa
- mtl
- linear
- JuicyPixels
- vector
- OpenGL
- GLFW-b
- accelerate
- accelerate-io
- primitive
- linear-accelerate
- JuicyPixels-extra
- directory
- bytestring
- word24

library:
  source-dirs: src

executables:
  pipes-graphics-accelerate-exe:
    main:                Main.hs
    source-dirs:         app/accelerate
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pipes-graphics

  pipes-graphics-repa-exe:
    main:                Main.hs
    source-dirs:         app/repa
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pipes-graphics

tests:
  pipes-graphics-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pipes-graphics
